# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90fbfe22f41a62a7ad589e0758923108ab93877b95826f67b8c61408613841040b5a3df1f8bfb8c1dbd2ca10a93edb0553d4e2d8e1e1d080964171c982c06d92

test:
  secret_key_base: fb9c914b7609bff6b66e1ecb3b067d49aaf510ec1aace524fb4389210b0146f99859b7179529f60cd1ae9ab35a76c109d0b6b8ebe7296ac2f682072a6aeb1cc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
